// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// opentherm_rx //
// ------------ //

#define opentherm_rx_wrap_target 0
#define opentherm_rx_wrap 15
#define opentherm_rx_pio_version 0

#define opentherm_rx_offset_wait_for_start 0u

static const uint16_t opentherm_rx_program_instructions[] = {
            //     .wrap_target
    0x20a0, //  0: wait   1 pin, 0
    0xe03f, //  1: set    x, 31
    0xaf42, //  2: nop                           [15]
    0x4001, //  3: in     pins, 1
    0xbf42, //  4: nop                           [31]
    0x4001, //  5: in     pins, 1
    0xaf42, //  6: nop                           [15]
    0x4001, //  7: in     pins, 1
    0xbf42, //  8: nop                           [31]
    0x4001, //  9: in     pins, 1
    0x0046, // 10: jmp    x--, 6
    0xaf42, // 11: nop                           [15]
    0x4001, // 12: in     pins, 1
    0xbf42, // 13: nop                           [31]
    0x4001, // 14: in     pins, 1
    0x8020, // 15: push   block
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program opentherm_rx_program = {
    .instructions = opentherm_rx_program_instructions,
    .length = 16,
    .origin = -1,
    .pio_version = opentherm_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config opentherm_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + opentherm_rx_wrap_target, offset + opentherm_rx_wrap);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
static inline void opentherm_rx_program_init(PIO pio, uint sm, uint offset, uint pin) {
    // Configure the pin as a PIO input
    pio_gpio_init(pio, pin);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, false);
    // Get default config
    pio_sm_config c = opentherm_rx_program_get_default_config(offset);
    // Map the IN pin group to our GPIO
    sm_config_set_in_pins(&c, pin);
    // Configure clock divider for 1kHz bit rate with Manchester encoding
    // Same timing as TX
    float div = clock_get_hz(clk_sys) / (2000000.0f);
    sm_config_set_clkdiv(&c, div);
    // Shift in bits MSB first, autopush after 32 bits
    sm_config_set_in_shift(&c, false, true, 32);
    // Initialize and enable the state machine
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}
// Helper function to check if data is available
static inline bool opentherm_rx_available(PIO pio, uint sm) {
    return !pio_sm_is_rx_fifo_empty(pio, sm);
}
// Helper function to receive raw Manchester-encoded data
static inline uint64_t opentherm_rx_get_raw(PIO pio, uint sm) {
    uint32_t first_word = pio_sm_get_blocking(pio, sm);
    uint32_t second_word = pio_sm_get_blocking(pio, sm);
    return ((uint64_t)first_word << 32) | second_word;
}

#endif

