// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// opentherm_tx //
// ------------ //

#define opentherm_tx_wrap_target 0
#define opentherm_tx_wrap 14
#define opentherm_tx_pio_version 0

#define opentherm_tx_IDLE 0
#define opentherm_tx_ACTIVE 1

#define opentherm_tx_offset_start 0u

static const uint16_t opentherm_tx_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xe03f, //  1: set    x, 31
    0xff01, //  2: set    pins, 1                [31]
    0xff00, //  3: set    pins, 0                [31]
    0x6041, //  4: out    y, 1
    0x0069, //  5: jmp    !y, 9
    0xff01, //  6: set    pins, 1                [31]
    0xff00, //  7: set    pins, 0                [31]
    0x000b, //  8: jmp    11
    0xff00, //  9: set    pins, 0                [31]
    0xff01, // 10: set    pins, 1                [31]
    0x0044, // 11: jmp    x--, 4
    0xff01, // 12: set    pins, 1                [31]
    0xff00, // 13: set    pins, 0                [31]
    0x0000, // 14: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program opentherm_tx_program = {
    .instructions = opentherm_tx_program_instructions,
    .length = 15,
    .origin = -1,
    .pio_version = opentherm_tx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config opentherm_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + opentherm_tx_wrap_target, offset + opentherm_tx_wrap);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
static inline void opentherm_tx_program_init(PIO pio, uint sm, uint offset, uint pin) {
    // Configure the pin as a PIO output
    pio_gpio_init(pio, pin);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    // Get default config
    pio_sm_config c = opentherm_tx_program_get_default_config(offset);
    // Map the SET pin group to our GPIO
    sm_config_set_set_pins(&c, pin, 1);
    // Set the pin to idle state initially (low)
    pio_sm_set_pins_with_mask(pio, sm, 0, (1u << pin));
    // Configure clock divider for proper timing
    // We need each instruction with [31] delay to take 500us
    // 32 cycles at the PIO clock should equal 500us
    // PIO clock = 125MHz / divider
    // We want: 32 / (125MHz / divider) = 500us
    // So: divider = 32 / (500us * 125MHz) = 32 / 62.5 = 0.512
    // But we need to account for the instruction itself (1 cycle)
    // So 32 delay cycles + 1 instruction = 33 cycles for 500us
    // divider = 33 / 62.5 = 0.528, let's use a bit higher for safety
    float div = clock_get_hz(clk_sys) / (66000.0f);  // ~66kHz PIO clock for 500us per 33 cycles
    sm_config_set_clkdiv(&c, div);
    // Shift out bits MSB first
    sm_config_set_out_shift(&c, false, false, 32);
    // Initialize and enable the state machine
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}
// Helper function to send an OpenTherm frame
static inline void opentherm_tx_send_frame(PIO pio, uint sm, uint32_t frame) {
    pio_sm_put_blocking(pio, sm, frame);
}

#endif

